FROM node:20-alpine
WORKDIR /app

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

COPY package.json package-lock.json* pnpm-lock.yaml* ./
RUN npm install

COPY . .
EXPOSE 5000
CMD ["sh", "-c", "npm run dev:server"]
